import { useEffect, useState } from "react";
import { useNavigate, useParams } from "react-router-dom";

import DashboardLayout from "@/layouts/DashboardLayout";
import { getResumeById } from "@/services/resumeService";

import {
    FileText,
    Calendar,
    ArrowLeft,
    PlayCircle,
    CheckCircle2,
} from "lucide-react";

import toast from "react-hot-toast";

export default function ResumeDetails() {

    const { id } = useParams();

    const navigate = useNavigate();

    const [resume, setResume] = useState(null);

    const [loading, setLoading] = useState(true);

    useEffect(() => {
        loadResume();
    }, []);

    const loadResume = async () => {

        try {

            const data = await getResumeById(id);

            setResume(data);

        } catch (e) {

            console.error(e);

            toast.error("Unable to load resume.");

        } finally {

            setLoading(false);

        }

    };

    if (loading) {

        return (
            <DashboardLayout>
                <div className="p-12 text-center">
                    Loading...
                </div>
            </DashboardLayout>
        );

    }

    return (

        <DashboardLayout>

            <div className="mx-auto max-w-6xl space-y-8">

                <div className="flex items-center justify-between">

                    <div>

                        <h1 className="text-4xl font-bold">

                            AI Resume Analysis

                        </h1>

                        <p className="mt-2 text-slate-500">

                            Detailed analysis generated by AI.

                        </p>

                    </div>

                    <button
                        onClick={() => navigate("/resume")}
                        className="flex items-center gap-2 rounded-xl border px-5 py-3 hover:bg-slate-100"
                    >

                        <ArrowLeft size={18} />

                        Back

                    </button>

                </div>

                {/* Header */}

                <div className="rounded-3xl bg-white p-8 shadow">

                    <div className="flex items-center gap-5">

                        <div className="rounded-2xl bg-indigo-100 p-4">

                            <FileText
                                className="text-indigo-600"
                                size={34}
                            />

                        </div>

                        <div>

                            <h2 className="text-2xl font-bold">

                                {resume.fileName}

                            </h2>

                            <div className="mt-2 flex items-center gap-5 text-slate-500">

                                <Calendar size={18} />

                                {new Date(
                                    resume.uploadedAt
                                ).toLocaleString()}

                            </div>

                        </div>

                    </div>

                </div>

                {/* Scores */}

                <div className="grid gap-6 md:grid-cols-2">

                    <div className="rounded-3xl bg-white p-8 shadow">

                        <h2 className="text-5xl font-bold text-indigo-600">

                            {resume.resumeScore}%

                        </h2>

                        <p className="mt-3 text-slate-500">

                            Resume Score

                        </p>

                    </div>

                    <div className="rounded-3xl bg-white p-8 shadow">

                        <h2 className="text-5xl font-bold text-green-600">

                            {resume.atsScore}%

                        </h2>

                        <p className="mt-3 text-slate-500">

                            ATS Score

                        </p>

                    </div>

                </div>

                {/* Experience */}

                <div className="rounded-3xl bg-white p-8 shadow">

                    <h2 className="mb-4 text-2xl font-bold">

                        Experience Summary

                    </h2>

                    <p className="leading-8 text-slate-600">

                        {resume.experienceSummary}

                    </p>

                </div>

                {/* Skills */}

                <div className="rounded-3xl bg-white p-8 shadow">

                    <h2 className="mb-5 text-2xl font-bold">

                        Skills

                    </h2>

                    <div className="flex flex-wrap gap-3">

                        {resume.skills.map(skill => (

                            <span
                                key={skill}
                                className="rounded-full bg-indigo-100 px-4 py-2 text-indigo-600"
                            >
                                {skill}
                            </span>

                        ))}

                    </div>

                </div>

                {/* Strengths */}

                <div className="rounded-3xl bg-white p-8 shadow">

                    <h2 className="mb-5 text-2xl font-bold text-green-700">

                        Strengths

                    </h2>

                    <ul className="space-y-3">

                        {resume.strengths.map(item => (

                            <li
                                key={item}
                                className="flex gap-3"
                            >

                                <CheckCircle2
                                    size={18}
                                    className="mt-1 text-green-600"
                                />

                                {item}

                            </li>

                        ))}

                    </ul>

                </div>

                {/* Weaknesses */}

                <div className="rounded-3xl bg-white p-8 shadow">

                    <h2 className="mb-5 text-2xl font-bold text-red-700">

                        Areas for Improvement

                    </h2>

                    <ul className="list-disc space-y-2 pl-6">

                        {resume.weaknesses.map(item => (

                            <li key={item}>{item}</li>

                        ))}

                    </ul>

                </div>

                {/* Recommendations */}

                <div className="rounded-3xl bg-white p-8 shadow">

                    <h2 className="mb-5 text-2xl font-bold">

                        AI Recommendations

                    </h2>

                    <ul className="list-disc space-y-2 pl-6">

                        {resume.recommendations.map(item => (

                            <li key={item}>{item}</li>

                        ))}

                    </ul>

                </div>

                {/* Missing Keywords */}

                <div className="rounded-3xl bg-white p-8 shadow">

                    <h2 className="mb-5 text-2xl font-bold">

                        Missing ATS Keywords

                    </h2>

                    <div className="flex flex-wrap gap-3">

                        {resume.missingKeywords.map(keyword => (

                            <span
                                key={keyword}
                                className="rounded-full bg-red-100 px-4 py-2 text-red-600"
                            >

                                {keyword}

                            </span>

                        ))}

                    </div>

                </div>

                {/* Suggested Interview Topics */}

                <div className="rounded-3xl bg-white p-8 shadow">

                    <h2 className="mb-5 text-2xl font-bold">

                        Suggested Interview Topics

                    </h2>

                    <div className="flex flex-wrap gap-3">

                        {resume.suggestedInterviewTopics.map(topic => (

                            <span
                                key={topic}
                                className="rounded-full bg-amber-100 px-4 py-2 text-amber-700"
                            >

                                {topic}

                            </span>

                        ))}

                    </div>

                </div>

                <button
                    onClick={() =>
                        navigate("/interview", {
                            state: {
                                resumeId: resume.id,
                            },
                        })
                    }
                    className="flex items-center gap-3 rounded-xl bg-indigo-600 px-8 py-4 text-white"
                >

                    <PlayCircle />

                    Start AI Interview

                </button>

            </div>

        </DashboardLayout>

    );

}